apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx

---

apiVersion: v1
kind: Route
metadata:
  name: my-nginx-router
  labels:
    app: nginx
spec:
  to:
    kind: Service
    name: my-nginx-svc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/var/cache/nginx"
        name: cache
      - mountPath: "/usr/share/nginx/html"
        name: mypd
  volumes:
    - name: cache
    - name: mypd
      persistentVolumeClaim:
       claimName: nginx-claim

